# Test all certificate combinations (rsa-rsa, rsa-dsa, dsa-rsa, etc.)
# Random values for fields, push specifications
# All exceptions
# to/from file and string
# Generated by ssh-keygen and decoded by script, created by script and verified by ssh-keygen

# import unittest
# from random import randint

# from src.sshkey_tools.keys import (
#     PrivateKey,
#     PublicKey,
#     RSAPrivateKey,
#     RSAPublicKey,
#     DSAPrivateKey,
#     DSAPublicKey,
#     ECDSAPrivateKey,
#     ECDSAPublicKey,
#     ED25519PrivateKey,
#     ED25519PublicKey
# )

# from src.sshkey_tools.cert import (
#     SSHCertificate,
#     RSACertificate,
#     DSACertificate,
#     ECDSACertificate,
#     ED25519Certificate
# )

# EXT_KEYS = {
#     'rsa': [
#         'user',
#         'ca'
#     ],
#     'dsa': [
#         'user',
#         'ca'
#     ],
#     'ecdsa': [
        
#     ]
# }


# class TestCertificateGeneration(unittest.TestCase):
#     def setUp(self):
        
        
    
#     def test_rsa_certificates(self):
